config/routes.rb
Rails.application.routes.draw do

  resources :categories, only: [:index, :new, :show, :create]

  get 'users/new'

  get 'users/create'

  get 'users/edit'

  get 'pages/about' => 'pages#about'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, except: [:new]

  resources :articles

  root 'pages#home'

end

app/models/article.rb
class Article < ActiveRecord::Base

  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true
  validates :description, presence: true,
                          length: {minimum:10, maximum:300}
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    # @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page:5)
  end

  def create

    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end

  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def new
    @article = Article.new
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "article successfully deleted"
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own article"
      redirect_to root_path
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>

    <div class="row">
      <div class="col-xs-offset-2 col-xs-8">
        <div class="well well-lg">
          <div class="article-title">
            <%= link_to article.title, article_path(article) %>
          </div>
          <div class="article-body">
            <%= truncate(article.description, length:100) %>
            <div class="article-meta-details">
              <small>
                Created by: <%= article.user.username if article.user %>, <%= time_ago_in_words(article.created_at) %> ago, last updated <%= time_ago_in_words(article.updated_at) %> ago
              </small>
            </div>
          </div>

          <% if article.categories.any? %>
            <p>Categories: <%= render article.categories %></p>
          <% end %>

            <% if logged_in? && (current_user == article.user || current_user.admin? ) %>
              <div class="article-actions">
                <%= link_to 'Edit this article', edit_article_path(article), class:"btn btn-xs btn-primary" %>
                <%= link_to 'Delete this article',      article_path(article), method: :delete,
                            class:"btn btn-xs btn-danger",
                            data: {confirm:"Are you sure?"}%>
                </div>
            <% end %>
        </div>
      </div>
    </div>

<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj:@article %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class:'form-horizontal', role: 'form'}) do |f| %>

        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :title %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :title, class: 'form-control', placeholder: 'Title of article', autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :description %>
          </div>
          <div class="col-sm-8">
            <%= f.text_area :description, class: 'form-control', rows: 10, placeholder: 'Body of article' %>
          </div>
        </div>


        <div class="form-group">
          <div class="row">
            <div class="col-sm-offset-2 col-sm-8">
              <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|%>
                <% cb.label(class: 'checkbox-inline input_checkbox') {cb.check_box(class:'checkbox') + cb.text} %>
              <% end %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class:'btn btn-primary btn-lg' %>
          </div>
        </div>


    <% end %>
  </div>
</div>


<div class="col-xs-offset-4 col-xs-4">
  [ <%= link_to 'Cancel request and return articles listing', articles_path %> ]
</div>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/edit.html.erb
<h1 align="center">Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing All Articles</h1>

<%= will_paginate %>

<%= render 'article', obj:@articles %>

<%= will_paginate %>

app/views/articles/new.html.erb
<h1 align="center">Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">

  <% if @article.user %>

      <ul class="listing">
        <div class="row center">
          <div class="col-md-4 col-md-offset-4">
            <li>Created by:</li>
            <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
            <li class="article-title">
              <%= link_to @article.user.username, user_path(@article.user) %>
            </li>
            <li>
              <small><%= pluralize(@article.user.articles.count, 'article') %></small>
            </li>
          </div>
        </div>
      </ul>

  <% end %>

  <h4 class="center">
    <string>Description:</string>
  </h4>
  <hr/>
  <%= simple_format(@article.description) %>

  <% if @article.categories.any? %>
      <p>Categories: <%= render @article.categories %></p>
  <% end %>

  <div class="article-actions">

    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <%= link_to 'Edit this article', edit_article_path(@article), class:"btn btn-xs btn-primary" %>
        <%= link_to 'Delete this article',      article_path(@article), method: :delete,
                    class:"btn btn-xs btn-danger",
                    data: {confirm:"Are you sure?"}%>
    <% end %>

    <%= link_to 'View all articles', articles_path, class: 'btn btn-xs btn-success' %>
  </div>


</div>